name: Continuous Integration

on:
  pull_request:
    branches:
      - producao

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          cd back-end  # Navega para a pasta back-end
          python -m pip install --upgrade pip
          pip install -r back-end/requirements.txt  # Certifica-se de que o caminho para requirements.txt est치 correto

      - name: Run unit tests
        run: |
          cd back-end  # Garante que est치 no diret칩rio certo para rodar os testes
          python manage.py test

      - name: Trigger Render Deploy
        if: success()  # S칩 executa o deploy se os testes forem bem-sucedidos
        run: curl -X POST "$RENDER_DEPLOY_HOOK"
        env:
          RENDER_DEPLOY_HOOK: ${{ secrets.RENDER_DEPLOY_HOOK }}
